name: publish package

on:
  push:
    branches: [ master ]

env:
  TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
  TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        make deps
    - name: Build and publish
      run: |
        python3 setup.py sdist bdist_wheel
        python3 -m twine upload dist/*
